Location:
    Region:
      roleClass: AppBundle\Controller\Location\RegionController
      actions: ["view","edit","more"]
      key: region

    District:
      roleClass: AppBundle\Controller\Location\DistrictController
      actions: ["view"]
      key: district

    Wards:
      roleClass: AppBundle\Controller\Location\WardController
      actions: ["view"]
      key: ward

Data:
    SoilType:
      roleClass: AppBundle\Controller\Configuration\SoilTypeController
      actions: ["view","add","edit","delete"]
      key: soil-type

    CropsInRegion:
      roleClass: AppBundle\Controller\Data\CropsInRegionController
      actions: [ "view","add","edit","delete","bulk-upload" ]
      key: crops-in-region

Accounts:
    Users:
      roleClass: AppBundle\Controller\UserAccounts\UserController
      actions: ["view","add","edit","delete","info","approve","decline"]
      key: users

    Roles:
      roleClass: AppBundle\Controller\UserAccounts\RoleController
      actions: ["view","add","edit","delete"]
      key: role-configuration
